apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::390402535986:role/eksctl-expense-1-nodegroup-expense-NodeInstanceRole-LJMpHxmMlioQ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::390402535986:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-01-22T14:10:21Z"
  name: aws-auth
  namespace: kube-system
  uid: c57f00b4-4eaf-4ec7-9bb7-6eeae1de6b32
 